name: flutter_localisation
description: A small flutter test project to try out language handling an translations.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.1

flutter:
  uses-material-design: true